# Generated by Django 3.0.8 on 2020-07-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='workspace_url',
            new_name='emails',
        ),
        migrations.AddField(
            model_name='proposal',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='amount',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
