# Generated by Django 3.0.8 on 2020-07-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_auto_20200711_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.CharField(blank=True, max_length=150)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='proposal.Proposal')),
            ],
        ),
        migrations.DeleteModel(
            name='Vendors',
        ),
    ]
